version: "3.8"

services:
   database:
      image: mysql:8.0
      container_name: symfony_db
      environment:
         MYSQL_ROOT_PASSWORD: root
         MYSQL_DATABASE: symfony_db
      ports:
         - "3306:3306"
      volumes:
         - database_data:/var/lib/mysql

volumes:
   database_data:
